apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codelearn
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
  - cleanup-cronjob.yaml
  - networkpolicy-code-server-user.yaml
  - limitrange-code-server-user.yaml
