apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: code-server-user-ingress
  namespace: codelearn
spec:
  podSelector:
    matchLabels:
      app: code-server-user
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cloudflared
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: codelearn
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
